import fs from 'node:fs';
import { Bel } from '../interp/bel.js';
const bel = new Bel({ readFile: (p) => (fs.existsSync(p) ? new Uint8Array(fs.readFileSync(p)) : null) });
const cases = [
  ['(cons \'a \'b \'(c d))', '(a b c d)'],
  ['(append \'(a b) nil \'(c) \'(d e))', '(a b c d e)'],
  ['(snoc \'(a b) \'c \'d)', '(a b c d)'],
  ['(map + \'(1 2 3) \'(10 20 30 40))', '(11 22 33)'],
  ['((fn (x . ys) ys) 1 2 3)', '(2 3)'],
  ['((fn (x (o y 10)) (list x y)) 1)', '(1 10)'],
  ['((fn (x (o y (+ x 1))) (list x y)) 5)', '(5 6)'],
  ['((fn ((a b) c) (list a b c)) \'(1 2) 3)', '(1 2 3)'],
  ['((fn (x|int) x) 5)', '5'],
  ['(onerr \'bad ((fn (x|int) x) \'a))', 'bad'],
  ['(let (a . b) \'(1 2 3) b)', '(2 3)'],
  ['(with (a 1 b 2) (+ a b))', '3'],
  ['(withs (a 1 b (+ a 1)) b)', '2'],
  ['(let x \'(a b c) (set (cadr x) \'z) x)', '(a z c)'],
  ['(let x \'(a b c) (set (car (cdr (cdr x))) 9) x)', '(a b 9)'],
  ['(do (set zz 5) (++ zz) zz)', '6'],
  ['(let x nil (push 1 x) (push 2 x) x)', '(2 1)'],
  ['(ccc (fn (k) (+ 1 (k 10))))', '10'],
  ['(catch (throw 7) 8)', '7'],
  ['(onerr \'oops (car \'a))', 'oops'],
  ['(safe (car \'a))', 'nil'],
  ['(eif e (err \'boom) (list \'caught e) (list \'ok e))', '(caught boom)'],
  ['(let acc nil (for i 1 5 (push i acc)) acc)', '(5 4 3 2 1)'],
  ['(let n 0 (repeat 10 (set n (+ n 1))) n)', '10'],
  ['(let (i acc) (list 0 nil) (while (< i 3) (push i acc) (set i (+ i 1))) acc)', '(2 1 0)'],
  ['((afn (n) (if (= n 0) 1 (* n (self (- n 1))))) 10)', '3628800'],
  ['(let f (rfn f (n acc) (if (= n 0) acc (f (- n 1) (+ acc 1)))) (f 1000000 0))', '1000000'],
  ['(map [* _ 2] \'(1 2 3))', '(2 4 6)'],
  ['(car:cdr \'(1 2 3))', '2'],
  ['(~no 3)', 't'],
  ['(apply + 1 2 \'(3 4))', '10'],
  ['(sort < \'(3 1 2))', '(1 2 3)'],
  ['(case \'b a 1 b 2 3)', '2'],
  ['(aif (find even \'(1 3 4 5)) (+ it 1))', '5'],
  ['(iflet x nil 1 (+ 2 3) (* x 2))', '10'],
  ['(and 1 2 3)', '3'],
  ['(or nil nil 4)', '4'],
  ['(when t 1 2)', '2'],
  ['(unless nil 3)', '3'],
  ['(len "hello")', '5'],
  ['(nth 3 \'(a b c d))', 'c'],
  ['(3 \'(a b c d))', 'c'],
  ['(drop 2 \'(a b c d))', '(c d)'],
  ['(first 2 \'(a b c d))', '(a b)'],
  ['(cut "foobar" 2 4)', '"oob"'],
  ['(rev \'(1 2 3))', '(3 2 1)'],
  ['(= \'(a (b)) \'(a (b)))', 't'],
  ['(< 1 2 3)', 't'],
  ['(> 3 2 2)', 'nil'],
  ['(<= 1 1 2)', 't'],
  ['(/ 1 4)', '0.25'],
  ['(floor -1.5)', '-2'],
  ['(round 2.5)', '2'],
  ['(round 3.5)', '4'],
  ['(mod -7 3)', '2'],
  ['(max 3 9 2)', '9'],
  ['(prs \'a 1 "b" \\c)', '"a1bc"'],
  ['(sym "foo")', 'foo'],
  ['(nom \'bar)', '"bar"'],
  ['(charn \\a)', '97'],
  ['(nchar 65)', '\\A'],
  ['(read \'("(a b . c)"))', '(a b . c)'],
  ['(let tab (table) (set (tab \'x) 1) (tab \'x))', '1'],
  ['(let a (array \'(3) 0) (a 2))', '0'],
  ['(mac twice (x) `(do ,x ,x))', null],
  ['(let n 0 (twice (set n (+ n 1))) n)', '2'],
  ['(dedup \'(a b a c b))', '(a b c)'],
  ['(keep odd \'(1 2 3 4 5))', '(1 3 5)'],
  ['(foldl + 0 \'(1 2 3))', '6'],
  ['(foldr cons nil \'(1 2 3))', '(1 2 3)'],
  ['(let x 1 (bind x 2 (list x)))', '(2)'],
  ['(type \\a)', 'char'],
  ['(isa!clo (fn (x) x))', 't'],
  ['(function car)', 'prim'],
  ['(let x \'(1 2 3) (zap + (car x) 10) x)', '(11 2 3)'],
  ['(accum a (each x \'(1 2 3) (a (* x x))))', '(1 4 9)'],
  ['(nof 3 \'x)', '(x x x)'],
  ['(tokens "the quick fox")', '("the" "quick" "fox")'],
  ['(pairwise < \'(1 2 3))', 't'],
  ['(after 1 (set aft 2))', '1'],
  ['aft', '2'],
  ['(let x (list 1 2) (pop (cdr x)) x)', '(1)'],
  ['(til x (pop q) (no x) (push x r))', null],
  ['(string "abc")', 't'],
  ['((fn (x (o y x)) (len scope)) 1)', '2'],
  ['(let fn (fn args 42) (fn 3))', '42'],
  ['(onerr \'bad (let xs (list 1 2) (set (nth 0 xs) 99)))', 'bad'],
  ['(onerr \'bad (let xs (list 1 2) (set (nth 1.5 xs) 99)))', 'bad'],
  ['(onerr \'bad (let xs (list 1 2) (set (nth 9 xs) 99)))', 'bad'],
  ['(onerr \'bad (nchar -1))', 'bad'],
  ['(let q (newq) (bind outs q (prc \\a) (prc \\b)) (rdc q) (rdc q) (bind outs q (prc \\c) (prc \\d)) (car q))', '"cd"'],
  ['(list (inv 2) (recip 4))', '(-2 0.25)'],
  ['(let r nil (for i 1 3 (push (fn () i) r)) (map [_] r))', '(3 2 1)'],
  ['(let r nil (for i 1 10 (push i r) (set i (+ i 1))) r)', '(9 7 5 3 1)'],
  ['(let (r q) (list nil \'(1 2 3)) (til x (pop q) (no x) (push x r)) r)', '(3 2 1)'],
  ['(let r nil (loop i 0 (+ i 2) (< i 7) (push i r)) r)', '(6 4 2 0)'],
  ['(let n 0 (repeat 5 (set n (+ n 2))) n)', '10'],
  ['(case 3 1 \'one 3 \'three \'other)', 'three'],
  ['(case 9 1 \'one \'other)', 'other'],
  ['(with ((a b) \'(1 2) c 3) (list a b c))', '(1 2 3)'],
  ['(and)', 't'],
  ['(or)', 'nil'],
  ['(and 1 nil 3)', 'nil'],
  ['(let x 5 (when (> x 2) (set x 1) (+ x 10)))', '11'],
  ['(begins "foobar" "foo")', 't'],
  ['(pos \\c "abcd")', '3'],
  ['(> \\b \\a)', 't'],
  ['(< "abc" "abd")', 't'],
];
let fail = 0;
for (const [src, want] of cases) {
  let got;
  try { got = bel.print(bel.evalString(src)); } catch (e) { got = 'ERR ' + e.message; }
  if (want !== null && got !== want) { fail++; console.log('FAIL', src, '=>', got, 'want', want); }
}
console.log(`${cases.length - fail}/${cases.length} passed (tier ${bel.tier})`);
if (fail) process.exit(1);
// CDR-coding cache must stay correct across structural mutation
{
  const r = bel.print(bel.evalString(`(let xs (list 1 2 3 4 5 6 7 8 9 10 11 12)
     (let a (list (nth 11 xs) (nth 11 xs) (nth 11 xs) (nth 11 xs))
       (xdr (drop 9 xs) '(x y z))
       (list a (nth 11 xs) (nth 11 xs) (drop 9 xs) (len xs))))`));
  const want = '((11 11 11 11) x x (10 x y z) 13)';
  if (r !== want) { console.log('FAIL cdr cache', r, 'want', want); process.exit(1); }
  const ring = bel.print(bel.evalString(`(let xs (list 1 2 3 4 5) (xdr (lastcdr xs) xs) (list (nth 12 xs) (nth 12 xs) (nth 12 xs) (car (drop 23 xs)) (car (drop 23 xs))))`));
  if (ring !== '(2 2 2 4 4)') { console.log('FAIL ring cache', ring); process.exit(1); }
  console.log('cdr cache ok');
}
